### ISSUE TITLE
Need to use fresh value of StakingRewardPool

### ISSUE THREAD

**Issue by k06a** [EthereumCommonwealth/Cold-staking#10]
This line:
https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L223

Should use:
```solidity
address(this).balance.sub(TotalStakingAmount);
```
Instead of:
```solidity
StakingRewardPool
```

Because balance could be refilled by Treasure.

Auditing smart contracts in live stream: https://www.youtube.com/watch?v=efZY3_COaiE

Your CryptoManiacs :)

**Comment by Dexaran** [comment]
If I understand it correctly, then the issue you are talking about is that if someone deposited CLO into the contract with [DEBUG_donation()](https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L162) function then the output of  [stake_reward() constant returns](https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L212) function will be incorrect because the `StakingRewardPool` is only updated within the new_block() function ([here](https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L115)).

The issue is confirmed, however I think that it is better to insert the new_block() function into the `DEBUG_donation()` at L163 https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L163

**Comment by Dexaran** [comment]
I can classify this as a **minor observation, non-security issue (10,000 CLO)**

**Comment by k06a** [comment]
@Dexaran you can call `this.new_block()` to avoid `msg.value` substraction :)

**Comment by Dexaran** [comment]
Paid https://explorer2.callisto.network/tx/0xade142e4c815ab92efb0256ec3adabb5080de836b0869ad08ffc32634dc3b36e

**Comment by k06a** [comment]
@Dexaran thanks!
