### ISSUE TITLE
Forgot to reset time

### ISSUE THREAD

**Issue by k06a** [EthereumCommonwealth/Cold-staking#9]
Need to reset time as well:
https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L182

And in near this line:
https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L262

This action will also refund gas:
```solidity
staker[msg.sender].time = 0;
```

Auditing smart contracts in live stream: https://www.youtube.com/watch?v=efZY3_COaiE

Your CryptoManiacs :)

**Comment by RideSolo** [comment]
The time is reset here: https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L149

**Comment by k06a** [comment]
@RideSolo sure, no problem with logic here. Only with durty state and gas economy. Erasing values refunds the gas, why not to erase time?

**Comment by Dexaran** [comment]
@k06a 

Gas economy does not make sense, because the amount is incredibly small. This is a thousand times lower than one cent.

By keeping this variable we will be able to see when the staker performed actions with the contract for the last time, which can be useful in some cases. I know that it is possible to review transaction history, but watching the variable in the contract is easier.

I cannot say that your observation introduces real improvements here.

**Comment by k06a** [comment]
@Dexaran, I just saw no reason to keep time value without amount. And you’re right about transaction history, events are usually used for this purposes.
